# Generated by Django 6.1 on 2026-09-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carros',
            old_name='nome',
            new_name='carro',
        ),
    ]
